apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi
  volumeName: "plex-config-pv"